services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data

  chocar-svc:
    image: chocar-main-svc:latest
    build: 
      context: .
      dockerfile: src/ChocarService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=chocar
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres

  identity-svc:
    image: chocar-identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5001:80
    depends_on:
      - postgres
      
  # web-app:
  #   image: dlrchris1193/web-app
  #   build: 
  #     context: .
  #     dockerfile: frontend/web-app/Dockerfile
  #   volumes:
  #     - /var/lib/web/data
  #   environment:
  #     - NEXTAUTH_SECRET=secret
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - API_URL=http://chocar-svc/
  #     - NEXT_PUBLIC_NOTIFY_URL=http://chocar-svc:7001/notifications
  #     - ID_URL=http://localhost:5001
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - identity-svc
  #     - chocar-svc  